version: "3"
services:
  ecommerce-app:
    build: ${ECOMMERCE_SERVICE_PATH}/Docker/app/.
    container_name: ${ECOMMERCE_SERVICE_NAME}
    env_file:
      - ${ECOMMERCE_SERVICE_PATH}/Docker/app/.env
      - .env
    environment:
      - SEQUELIZE_HOST=${ECOMMERCE_MYSQL_NAME}
      - SEQUELIZE_DATABASE=${ECOMMERCE_MYSQL_DATABASE}
    volumes:
      - ${ECOMMERCE_SERVICE_PATH}/src:/app/src
    ports:
      - ${ECOMMERCE_APP_PORT}:8080
    depends_on:
      - ecommerce-mysql
    entrypoint: ["sh", "-c", "while ! nc -z ecommerce-mysql 3306; do sleep 1; done; npm run dev"]
  ecommerce-mysql:
    platform: linux/x86_64
    build: ${ECOMMERCE_SERVICE_PATH}/Docker/database/.
    restart: always
    container_name: ${ECOMMERCE_MYSQL_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${ECOMMERCE_MYSQL_DATABASE}
    ports:
      - ${ECOMMERCE_MYSQL_PORT}:3306
    command: ["mysqld", "--mysql-native-password=ON"]